branches:
  only:
    - master
version: '{build}'
clone_depth: 25
init:
- cmd: ''
environment:
  matrix:
  - PYTHON: C:\Python36-x64
    PATH: C:\Python36-x64\Scripts;%PATH%
  - PYTHON: C:\Python37-x64
    PATH: C:\Python37-x64\Scripts;%PATH%
install:
- cmd: >-
    curl -LfsS -o fictrac.zip https://github.com/murthylab/fictrac/releases/download/v2.0.2/fictrac_v2.0.2_control_features_x64_windows.zip
    
    7z x fictrac.zip -oc:\
    
    set PATH=%PATH%;C:\fictrac

    %PYTHON%\\python.exe -m pip install -e .[dev]
cache:
- '%PYTHON%\Scripts'
- '%PYTHON%\lib\site-packages'
build: off
test_script:
- cmd: '%PYTHON%\\python.exe -m pytest tests/'
